export const integrations = [
    { title: 'Graphlo', category: 'Productivity', description: 'Integrate with Graphlo to streamline your customer relationship management. Sync contacts, automate workflows, and gain insights with powerful analytics.', icon: 'assets/images/client/icons/05.svg', link: 'integration-single.html' },
    { title: 'Vectra', category: 'CRM', description: 'Seamless email marketing campaigns. Automate email sequences, manage subscriber lists, and track campaign performance.', icon: 'assets/images/client/icons/11.svg', link: 'integration-single.html' },
    { title: 'Signum', category: 'Payment', description: 'Integrate Signum for secure and efficient payment processing. Accept payments, manage subscriptions, and track transactions effortlessly.', icon: 'assets/images/client/icons/10.svg', link: 'integration-single.html' },
    { title: 'Grapherz', category: 'Streaming', description: 'Streamlined accounting and financial management. Track expenses, generate invoices, and manage payroll with ease.', icon: 'assets/images/client/icons/04.svg', link: 'integration-single.html' },
    { title: 'Imprintify', category: 'Productivity', description: 'Imprintify to enhance team communication and collaboration. Receive notifications, share updates, and manage tasks directly within imprintify.', icon: 'assets/images/client/icons/07.svg', link: 'integration-single.html' },
    { title: 'Logique', category: 'e-commerce', description: 'Connect with Logique to enhance your e-commerce operations. Sync inventory, manage orders, and track sales from one platform.', icon: 'assets/images/client/icons/08.svg', link: 'integration-single.html' },
    { title: 'Optimal', category: 'CRM', description: 'Integrate with Optimal to streamline your customer relationship management. Sync contacts, automate workflows, and gain insights with powerful analytics.', icon: 'assets/images/client/icons/09.svg', link: 'integration-single.html' },
    { title: 'Artistry', category: 'Payment', description: 'Manage support tickets, track customer interactions, and improve response times.', icon: 'assets/images/client/icons/01.svg', link: 'integration-single.html' },
    { title: 'Wayline', category: 'Streaming', description: 'Sync with Wayline for enhanced project management. Organize tasks, collaborate with your team, and track project progress effortlessly.', icon: 'assets/images/client/icons/03.svg', link: 'integration-single.html' }
];